apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: my-django-container
          image: khareutkarsh/master-django-app:lates
          ports:
            - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: my-django-service
spec:
  type: LoadBalancer
  selector:
    app: django-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
